# coding: utf-8

# flake8: noqa

"""
    Papermerge REST API

    Document management system designed for digital archives  # noqa: E501

    The version of the OpenAPI document: 2.1.0b12
    Generated by: https://openapi-generator.tech
"""

__version__ = "1.0.0"

# import ApiClient
from papermerge-restapi-client.api_client import ApiClient

# import Configuration
from papermerge-restapi-client.configuration import Configuration

# import exceptions
from papermerge-restapi-client.exceptions import OpenApiException
from papermerge-restapi-client.exceptions import ApiAttributeError
from papermerge-restapi-client.exceptions import ApiTypeError
from papermerge-restapi-client.exceptions import ApiValueError
from papermerge-restapi-client.exceptions import ApiKeyError
from papermerge-restapi-client.exceptions import ApiException
