# coding: utf-8

"""
    Papermerge REST API

    Document management system designed for digital archives  # noqa: E501

    The version of the OpenAPI document: 2.1.0b12
    Generated by: https://openapi-generator.tech
"""

import unittest

import papermerge-restapi-client
from papermerge-restapi-client.model.inbox_count import InboxCount
from papermerge-restapi-client import configuration


class TestInboxCount(unittest.TestCase):
    """InboxCount unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
