/**
 * Papermerge REST API
 * Document management system designed for digital archives
 *
 * The version of the OpenAPI document: 2.1.0b12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { DocumentDetailsDataRelationships } from './documentDetailsDataRelationships';
import { FolderDataAttributes } from './folderDataAttributes';

export class FolderData {
    'type': FolderData.TypeEnum;
    'id'?: string;
    'attributes'?: FolderDataAttributes;
    'relationships'?: DocumentDetailsDataRelationships;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "FolderData.TypeEnum"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "FolderDataAttributes"
        },
        {
            "name": "relationships",
            "baseName": "relationships",
            "type": "DocumentDetailsDataRelationships"
        }    ];

    static getAttributeTypeMap() {
        return FolderData.attributeTypeMap;
    }
}

export namespace FolderData {
    export enum TypeEnum {
        Folders = <any> 'folders'
    }
}
