/**
 * Papermerge REST API
 * Document management system designed for digital archives
 *
 * The version of the OpenAPI document: 2.1.0b12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { GroupDataAttributes } from './groupDataAttributes';
import { GroupDataRelationships } from './groupDataRelationships';

export class GroupData {
    'type': GroupData.TypeEnum;
    'id'?: string;
    'attributes'?: GroupDataAttributes;
    'relationships'?: GroupDataRelationships;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "GroupData.TypeEnum"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "GroupDataAttributes"
        },
        {
            "name": "relationships",
            "baseName": "relationships",
            "type": "GroupDataRelationships"
        }    ];

    static getAttributeTypeMap() {
        return GroupData.attributeTypeMap;
    }
}

export namespace GroupData {
    export enum TypeEnum {
        Groups = <any> 'groups'
    }
}
