/**
 * Papermerge REST API
 * Document management system designed for digital archives
 *
 * The version of the OpenAPI document: 2.1.0b12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ArchiveTypeEnum } from './archiveTypeEnum';
import { IncludeVersionEnum } from './includeVersionEnum';

export class NodesDownload {
    'nodeIds': Array<string>;
    'fileName'?: string;
    'includeVersion'?: IncludeVersionEnum;
    'archiveType'?: ArchiveTypeEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "nodeIds",
            "baseName": "node_ids",
            "type": "Array<string>"
        },
        {
            "name": "fileName",
            "baseName": "file_name",
            "type": "string"
        },
        {
            "name": "includeVersion",
            "baseName": "include_version",
            "type": "IncludeVersionEnum"
        },
        {
            "name": "archiveType",
            "baseName": "archive_type",
            "type": "ArchiveTypeEnum"
        }    ];

    static getAttributeTypeMap() {
        return NodesDownload.attributeTypeMap;
    }
}

