/**
 * Papermerge REST API
 * Document management system designed for digital archives
 *
 * The version of the OpenAPI document: 2.1.0b12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { NodeID } from './nodeID';

export class NodeMove {
    'targetParent': NodeID;
    'nodes': Array<NodeID>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "targetParent",
            "baseName": "target_parent",
            "type": "NodeID"
        },
        {
            "name": "nodes",
            "baseName": "nodes",
            "type": "Array<NodeID>"
        }    ];

    static getAttributeTypeMap() {
        return NodeMove.attributeTypeMap;
    }
}

