/**
 * Papermerge REST API
 * Document management system designed for digital archives
 *
 * The version of the OpenAPI document: 2.1.0b12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class PageReorder {
    'id': string;
    /**
    * Page position within the document before  page\'s order change.Position numbering starts with 1.
    */
    'oldNumber': number;
    /**
    * Desired new page position within the document. Position numbering starts with 1.
    */
    'newNumber': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "oldNumber",
            "baseName": "old_number",
            "type": "number"
        },
        {
            "name": "newNumber",
            "baseName": "new_number",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return PageReorder.attributeTypeMap;
    }
}

