/**
 * Papermerge REST API
 * Document management system designed for digital archives
 *
 * The version of the OpenAPI document: 2.1.0b12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PageDataAttributes } from './pageDataAttributes';
import { PageDataRelationships } from './pageDataRelationships';

export class PageData {
    'type': PageData.TypeEnum;
    'id'?: string;
    'attributes'?: PageDataAttributes;
    'relationships'?: PageDataRelationships;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "PageData.TypeEnum"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "PageDataAttributes"
        },
        {
            "name": "relationships",
            "baseName": "relationships",
            "type": "PageDataRelationships"
        }    ];

    static getAttributeTypeMap() {
        return PageData.attributeTypeMap;
    }
}

export namespace PageData {
    export enum TypeEnum {
        Pages = <any> 'pages'
    }
}
