/**
 * Papermerge REST API
 * Document management system designed for digital archives
 *
 * The version of the OpenAPI document: 2.1.0b12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class PageDataAttributes {
    'id'?: string;
    'number'?: number;
    'text'?: string;
    'lang'?: string;
    'svgUrl'?: string;
    'jpgUrl'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "number",
            "baseName": "number",
            "type": "number"
        },
        {
            "name": "text",
            "baseName": "text",
            "type": "string"
        },
        {
            "name": "lang",
            "baseName": "lang",
            "type": "string"
        },
        {
            "name": "svgUrl",
            "baseName": "svg_url",
            "type": "string"
        },
        {
            "name": "jpgUrl",
            "baseName": "jpg_url",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return PageDataAttributes.attributeTypeMap;
    }
}

