/**
 * Papermerge REST API
 * Document management system designed for digital archives
 *
 * The version of the OpenAPI document: 2.1.0b12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PaginatedCustomUserPreferenceListMetaPagination } from './paginatedCustomUserPreferenceListMetaPagination';

export class PaginatedCustomUserPreferenceListMeta {
    'pagination'?: PaginatedCustomUserPreferenceListMetaPagination;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "pagination",
            "baseName": "pagination",
            "type": "PaginatedCustomUserPreferenceListMetaPagination"
        }    ];

    static getAttributeTypeMap() {
        return PaginatedCustomUserPreferenceListMeta.attributeTypeMap;
    }
}

