/**
 * Papermerge REST API
 * Document management system designed for digital archives
 *
 * The version of the OpenAPI document: 2.1.0b12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Pageref } from './pageref';

export class Pagination {
    'first'?: Pageref;
    'last'?: Pageref;
    'prev'?: Pageref;
    'next'?: Pageref;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "first",
            "baseName": "first",
            "type": "Pageref"
        },
        {
            "name": "last",
            "baseName": "last",
            "type": "Pageref"
        },
        {
            "name": "prev",
            "baseName": "prev",
            "type": "Pageref"
        },
        {
            "name": "next",
            "baseName": "next",
            "type": "Pageref"
        }    ];

    static getAttributeTypeMap() {
        return Pagination.attributeTypeMap;
    }
}

