/**
 * Papermerge REST API
 * Document management system designed for digital archives
 *
 * The version of the OpenAPI document: 2.1.0b12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PatchedTagDataAttributes } from './patchedTagDataAttributes';

export class PatchedTagData {
    'type': PatchedTagData.TypeEnum;
    'id'?: string;
    'attributes'?: PatchedTagDataAttributes;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "PatchedTagData.TypeEnum"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "PatchedTagDataAttributes"
        }    ];

    static getAttributeTypeMap() {
        return PatchedTagData.attributeTypeMap;
    }
}

export namespace PatchedTagData {
    export enum TypeEnum {
        Tags = <any> 'tags'
    }
}
