/**
 * Papermerge REST API
 * Document management system designed for digital archives
 *
 * The version of the OpenAPI document: 2.1.0b12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PatchedUserDataAttributes } from './patchedUserDataAttributes';
import { PatchedUserDataRelationships } from './patchedUserDataRelationships';

export class PatchedUserData {
    'type': PatchedUserData.TypeEnum;
    'id'?: string;
    'attributes'?: PatchedUserDataAttributes;
    'relationships'?: PatchedUserDataRelationships;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "PatchedUserData.TypeEnum"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "PatchedUserDataAttributes"
        },
        {
            "name": "relationships",
            "baseName": "relationships",
            "type": "PatchedUserDataRelationships"
        }    ];

    static getAttributeTypeMap() {
        return PatchedUserData.attributeTypeMap;
    }
}

export namespace PatchedUserData {
    export enum TypeEnum {
        Users = <any> 'users'
    }
}
