/**
 * Papermerge REST API
 * Document management system designed for digital archives
 *
 * The version of the OpenAPI document: 2.1.0b12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Reltomany } from './reltomany';
import { Reltoone } from './reltoone';

export class PatchedUserDataRelationships {
    'inboxFolder'?: Reltoone;
    'homeFolder'?: Reltoone;
    'groups'?: Reltomany;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "inboxFolder",
            "baseName": "inbox_folder",
            "type": "Reltoone"
        },
        {
            "name": "homeFolder",
            "baseName": "home_folder",
            "type": "Reltoone"
        },
        {
            "name": "groups",
            "baseName": "groups",
            "type": "Reltomany"
        }    ];

    static getAttributeTypeMap() {
        return PatchedUserDataRelationships.attributeTypeMap;
    }
}

