/**
 * Papermerge REST API
 * Document management system designed for digital archives
 *
 * The version of the OpenAPI document: 2.1.0b12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class PatchedTagDataAttributes {
    'id'?: string;
    'name': string;
    'bgColor'?: string;
    'fgColor'?: string;
    'description'?: string | null;
    /**
    * Pinned tag will be displayed under Documents menu. It serves as shortcut to quickly filter folders/documents associated with this tag
    */
    'pinned'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "bgColor",
            "baseName": "bg_color",
            "type": "string"
        },
        {
            "name": "fgColor",
            "baseName": "fg_color",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "pinned",
            "baseName": "pinned",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return PatchedTagDataAttributes.attributeTypeMap;
    }
}

