/**
 * Papermerge REST API
 * Document management system designed for digital archives
 *
 * The version of the OpenAPI document: 2.1.0b12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Link } from './link';

/**
* optional references to other resource objects
*/
export class RelationshipLinks extends null<String, any> {
    'self'?: Link;
    'related'?: Link;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "self",
            "baseName": "self",
            "type": "Link"
        },
        {
            "name": "related",
            "baseName": "related",
            "type": "Link"
        }    ];

    static getAttributeTypeMap() {
        return super.getAttributeTypeMap().concat(RelationshipLinks.attributeTypeMap);
    }
}

