/**
 * Papermerge REST API
 * Document management system designed for digital archives
 *
 * The version of the OpenAPI document: 2.1.0b12
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { TokenDataAttributes } from './tokenDataAttributes';

export class TokenData {
    'type': TokenData.TypeEnum;
    'id'?: string;
    'attributes'?: TokenDataAttributes;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "TokenData.TypeEnum"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "TokenDataAttributes"
        }    ];

    static getAttributeTypeMap() {
        return TokenData.attributeTypeMap;
    }
}

export namespace TokenData {
    export enum TypeEnum {
        Tokens = <any> 'tokens'
    }
}
